name: "fullstack"

services:
  frontend:
    image: joseluisq/static-web-server:2
    volumes:
      # Vertsystemet  :   Containersiden
      - ./frontend:/public
    ports:
      - 8080:80

  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    ports:
      - 9090:8080

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example

  postgres-web-ui:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 18080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.to
      PGADMIN_DEFAULT_PASSWORD: example
