name: "fullstack"

services:
  frontend:
    image: joseluisq/static-web-server:2
    volumes:
      - ./frontend:/public
    ports:
      - 8080:80

  static-dotnet:
    build:
      context: ./StaticServer
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/App/wwwroot
    ports:
      - 9090:8080
