name: "fullstack"

services:
  frontend:
    image: joseluisq/static-web-server:2
    volumes:
      # Vertsystemet  :   Containersiden
      - ./frontend:/public
    ports:
      - 8080:80

  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    ports:
      - 9090:8080
